FROM ubuntu:20.04

# Install Python
RUN apt-get update && apt-get install -y python3 python3-pip

# Install Node.js
RUN apt-get install -y nodejs npm

# Install Java
RUN apt-get install -y openjdk-11-jdk

# Install GCC (C and C++)
RUN apt-get install -y gcc g++

# Install Ruby
RUN apt-get install -y ruby-full

# Install Go
RUN apt-get install -y golang-go

# Install PHP
RUN apt-get install -y php

# Install .NET SDK for C#
RUN apt-get install -y wget && \
    wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y dotnet-sdk-5.0

# Install Swift
RUN apt-get install -y clang libicu-dev libcurl4-openssl-dev libssl-dev && \
    wget https://swift.org/builds/swift-5.4-release/ubuntu2004/swift-5.4-RELEASE/swift-5.4-RELEASE-ubuntu20.04.tar.gz && \
    tar xzf swift-5.4-RELEASE-ubuntu20.04.tar.gz && \
    mv swift-5.4-RELEASE-ubuntu20.04 /usr/share/swift && \
    ln -s /usr/share/swift/usr/bin/swift /usr/bin/swift

WORKDIR /app
